theme: jekyll-theme-minimal
title: Statistical problem
description: 回归分析、生存分析、主成分分析（Principal component analysis）、聚类分析（Cluster analysis）、数据降维[Uniform Manifold Approximation and Projection(UMAP)、t-Distributed Stochastic Neighbor Embedding (t-SNE)]、统计检验等的笔记。
