project:
  type: book
  output-dir: docs

book:
  title: "应用医学统计学"
  reader-mode: true
  
  chapters:
    - index.qmd

    - part: data_science.qmd

    - part: "统计描述"
      chapters:
        - statistical_description.qmd

    # - part: "统计推断"
    #   chapters:
    #     - sampling_bootstrapping.qmd
    #     - parameterEstimation.qmd
    #     - hypothesisTesting.qmd
    #     - PowerAnalysis.qmd
    #     - Causal_Inference.qmd
    #     
    # - part: "统计学习和建模"
    #   chapters:   
    #     - Regression.qmd
    #     - Classification.qmd
    #     - Clustering.qmd
    #     - DimensionalityReduction.qmd

    - part: "生存分析"
      chapters:
        - SurvivalAnalysis.qmd



execute:
  cache: true
  error: true
  message: FALSE
  warning: false
  
toc: true
toc-expand: true
toc-depth: 4
toc-location: right
number-sections: true

knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE
    
crossref: 
  fig-title: 图
  fig-prefix: 图
  
format: 
  html: 
    theme: cosmo
    df-print: kable
    code-fold: true
    code-tools: true
    code-link: true
    html-math-method: katex

    
editor: visual


