project:
  type: book
  output-dir: docs

book:
  title: "医学与生物统计学"
  reader-mode: true
  
  chapters:
    - index.qmd

    - part: data_science.qmd

    - part: "统计描述"
      chapters:
        - descriptive_statistics.qmd

    - part: "概率论"
      chapters:
        - probability_fundamentals.qmd

    #    - sampling_bootstrapping.qmd
    # - part: "统计推断"
    #   chapters:
    #     - sampling_bootstrapping.qmd
    #     - parameterEstimation.qmd
    #     - hypothesis_testing.qmd
    #     - PowerAnalysis.qmd
    #     - Causal_Inference.qmd
    #     
    # - part: "统计建模"
    #   chapters:   
    #     - Regression.qmd
    #     - Classification.qmd
    #     - Clustering.qmd
    #     - DimensionalityReduction.qmd

    - part: "生存分析"
      chapters:
        - SurvivalAnalysis.qmd



execute:
  cache: true
  error: true
  message: FALSE
  warning: false
  
toc: true
toc-expand: true
toc-depth: 4
toc-location: right
number-sections: true
number-depth: 4

knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE
    
crossref: 
  fig-title: 图
  fig-prefix: 图
  
format: 
  html: 
    theme: cosmo
    df-print: kable
    code-fold: true
    code-tools: true
    code-link: true
    html-math-method: katex

    
editor: visual


