project:
  type: book
  output-dir: docs

book:
  title: "医学与生物统计学"
  reader-mode: true
  
  chapters:
    - index.qmd

    - part: "统计描述"
      chapters:
        - descriptive_statistics.qmd

    - part: "统计推断"
      chapters:
        - hypothesis_test.qmd
        - ANOVA.qmd
        - independence_correlation.qmd
        - nonparametric_test.qmd

    #     - PowerAnalysis.qmd
    #     - Causal_Inference.qmd
    - part: "统计建模"
      chapters:
        - LinearRegression.qmd
        - glm.qmd

    - part: "生存分析"
      chapters:
        - SurvivalAnalysis.qmd


    - part: "机器学习"
      chapters:
        - Clustering.qmd
        - PCA.qmd
        - t-SNE.qmd
        - UMAP.qmd

    - part: "临床统计"
      chapters: 
        - diagnostic_tests.qmd
        - observational_study_design.qmd


    - part: "附录1：理论基础"
      chapters:
        - 概率论基础.qmd
        - SamplingDistribution.qmd
        - ParameterEstimation.qmd
        - 线性代数基础.qmd

execute:
  cache: true
  message: false
  warning: false
  
toc: true
toc-expand: true
toc-depth: 4
toc-location: right
number-sections: true
number-depth: 4

knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE
    
crossref: 
  fig-title: 图
  fig-prefix: 图
  tbl-title: 表
  tbl-prefix: 表
  
format: 
  html: 
    theme: cosmo
    css: styles.css
    df-print: kable
    code-fold: true
    code-tools: true
    code-link: true
    html-math-method: mathjax

    
editor: visual


