project:
  type: book
  output-dir: docs

book:
  title: "BioStatistics"
  author: "王安林"
  date: "2024/3/7"
  reader-mode: true
  chapters:
    - index.qmd
    - intro.qmd
    - part: "统计描述"

    - part: "统计推断"
      chapters:
        - parameterEstimation.qmd
        - hypothesisTesting.qmd
        - RegressionAnalysis.qmd
        - classification.qmd
        - ClusterAnalysis.qmd
        - DimensionReduction.qmd
        
    - SurvivalAnalysis.qmd
    
    - summary.qmd
    - references.qmd
    
    
  repo-url: https://github.com/Wanganlin00/Biostatistics/
  repo-actions: [edit,issue]
    

bibliography: references.bib

execute:
  cache: true
  error: true
  message: FALSE
  warning: false
toc: true
toc-expand: true
toc-depth: 4
toc-location: right
number-sections: true
knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE
crossref: 
  fig-title: 图
  fig-prefix: 图
  
fig-width: 6
fig-asp: 0.618

format: 
  html: 
    theme: cosmo
    df-print: kable
    code-fold: true
    code-tools: true
    code-link: true
    html-math-method: katex
#  pdf: 
#    documentclass: scrreprt
    

editor: visual


